### ISSUE TITLE
Authoritative location for Wasm OCI spec

### ISSUE THREAD

**Issue by craigbox** [solo-io/wasm#176]
Which of

* https://github.com/solo-io/wasm/blob/master/spec/README.md
* https://github.com/solo-io/wasm-image-spec/blob/master/README.md

is correct?

**Comment by Sodman** [comment]
Hi @craigbox, https://github.com/solo-io/wasm/blob/master/spec/README.md is the authoritative source now.

We have moved from the `wasm-image-spec` repo to here, so that we have one consolidated location for folks to find the wasm OCI spec, the sdks, and the cli tools like wasme.

I will update the old repo to make it clear that the spec has moved to this repo.
