### ISSUE TITLE
wasme support for rust

### ISSUE THREAD

**Issue by invent360** [solo-io/wasm#234]
Have the support for rust been halted completely ?
i went to the documentation page (https://docs.solo.io/web-assembly-hub/latest/tutorial_code/build_tutorials/) and only saw support for Assemblyscript and C++.
<img width="988" alt="Screenshot 2021-01-30 at 05 05 35" src="https://user-images.githubusercontent.com/46233704/106347788-ecb93f80-62b8-11eb-8f52-f6a78a92584c.png">

**Comment by Sodman** [comment]
Hi @invent360, the proxy-wasm rust SDK is still supported by wasme. If you run `wasme init`, you'll still see `rust` as an option.

The cpp example is meant to be a general example of creating / building / tagging a wasm filter for Envoy, using `wasme`. All of these instructions should basically be the same for any of the other target languages, the output filter will just look a little different depending on the language chosen.

The AssemblyScript proxy runtime has it's own example in our docs because solo.io actively maintains that repo - https://github.com/solo-io/proxy-runtime

If you're looking for examples on writing filters in other languages, you should check out the upstream docs, as they'll likely be more up to date with the latest changes to the upstream SDKs. For example, here's the rust SDK repo, which has a few filter examples in it - https://github.com/proxy-wasm/proxy-wasm-rust-sdk

**Comment by Sodman** [comment]
Closing this one out, feel free to open a new issue if you have further questions!

**Comment by invent360** [comment]
@Sodman Thanks so much for your help, really appreciate it.
